const mongoose = require('mongoose');

const useOfForceSchema = new mongoose.Schema({
  'Blunt Object': String,
  'Category of Force Event - Measured at Event Level': String,
  'Disposition/Custody': String,
  'DOW': String,
  'Firearm': String,
  'Firearm - Implied': String,
  'Firearm - Replica': String,
  'Force Applied - 1': String,
  'Force Applied - 2': String,
  'Force Applied - 3': String,
  'Force Applied - 4': String,
  'Force Applied - 5': String,
  'Force Applied - 6': String,
  'Force Applied - 7': String,
  'Force Applied - 8': String,
  'Hour (6Hr)': String,
  'Initial Call Category': String,
  'Initial Call type': String,
  'Knife / Edged Weapon / Stabbing Instrument': String,
  'Mental Health Crisis - Prior to Force, Perceived Lack of Compliance': String,
  'Month': String,
  'Needle / Spit / Bodily Fluids': String,
  'No weapon (unarmed)': String,
  'Officer': String,
  'Officer Precinct': String,
  'Officer Tenure': String,
  'Other Weapon': String,
  'Record ID': String,
  'Subject': String,
  'Subject - Race': String,
  'Subject - Sex': String,
  'Subject - Transient': String,
  'Subject Age': String,
  'Subject Instance': String,
  'Subject Resistance - 1': String,
  'Subject Resistance - 2': String,
  'Subject Resistance - 3': String,
  'Subject Resistance - 4': String,
  'Subject Resistance - 5': String,
  'Subject Resistance - 6': String,
  'Subject Resistance - 7': String,
  'Subject Resistance - 8': String,
  'Under the Influence of Alcohol - Prior to Force, Perceived Condition': String,
  'Under the Influence of Drugs - Prior to Force, Perceived Condition': String,
  'Weapon Present or reported but not used or threatened use': String,
  'Year': String,
});

module.exports = mongoose.model('UseOfForce', useOfForceSchema);
